language: cpp

_sources: &repos
  - ubuntu-toolchain-r-test
  - llvm-toolchain-trusty
  - llvm-toolchain-trusty-4.0
  - llvm-toolchain-trusty-5.0

_addons: &addon_conf
  apt:
    packages: ['gcc-multilib']
    sources: *repos

env:
  global:
    - TC_HOME=$HOME/tc

matrix:
  include:
   - os: linux
     env: ARMGCC_VERSION="7.3.1" BOARD=DISCO_L475VG_IOT01A

before_install:
  - pip install --user mbed-cli
  - mbed deploy
  - pip install --user -r mbed-os/requirements.txt
  - mbed new .
  - ls -la . && ls -la mbed-ci/
  - chmod +x mbed-ci/toolchain_install.sh && . mbed-ci/toolchain_install.sh && linux_default_download

script:
  - mbed compile -t GCC_ARM -m ${BOARD}

cache:
  directories:
    - ${TC_HOME}
